#!/bin/sh

# Set aliases common across operating systems.
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cp="cp -ip"
alias crontab="VIM_CRONTAB=true crontab"
alias desktop="cd ~/Desktop"
alias df="df -h --total"
alias extip="curl -sS eth0.me"
alias fgrep="fgrep --color=auto"
alias gitroot='cd ./$(git rev-parse --show-cdup) && ll'
alias grep="grep --color=auto"
alias htop="sudo htop"
alias iftop="sudo iftop -B"
alias ls="ls -N --color=auto"
alias ll="ls -lh"
alias la="ls -lah"
alias mkdir="mkdir -pv"
alias mv="mv -i"
alias path='echo -e ${PATH//:/\\n}'
alias ping='ping -c 5'
alias ports="sudo lsof -iTCP -sTCP:LISTEN -n -P"
alias projects="cd ~/Developer/Projects"
alias reload="source ~/.zshrc"
alias rsync="rsync -avrz --progress --exclude=.DS_Store"
alias space="df -h --total"
alias starWars="telnet towel.blinkenlights.nl"
alias tailf="tail -f"
alias top="htop"
alias weather="curl wttr.in"

# Retrieve the operating system information.
OS=`uname`

# Set OSX specific aliases.
if [[ "$OS" == 'Darwin' ]]; then
    alias chrome="open -a \"Google Chrome\""
    alias lock="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
    alias update="brew update"
    alias upgrade="brew upgrade"
fi

