#!/bin/sh

########################################################################
#  Functions
#  https://github.com/ryanmcdowell/dotfiles
#
#  Utility functions to simplify CLI usage.
#
########################################################################

