#!/bin/sh

########################################################################
#  Motd
#
#  Displays the message of the day at the start of each terminal
#  session.
#
########################################################################

# Clear existing screen's contents.
clear

# Output a spacer line.
echo

# Display archey
archey --color --offline
