#!/bin/sh

########################################################################
#  Motd
#
#  Displays the message of the day at the start of each terminal
#  session.
#
########################################################################

# Clear existing screen's contents.
clear

# Output a spacer line.
echo

# Display archey
if [[ "$OS" == 'Darwin' ]]; then
  archey --color --offline
elif [[ "$OS" == 'Linux' ]]; then
  archey
fi
