#!/bin/sh

########################################################################
#  Motd
#
#  Displays the message of the day at the start of each terminal
#  session.
#
########################################################################

# Clear existing screen's contents.
clear

# Output a spacer
printf "\n\n"

# Display archey
archey

# Output a spacer
printf "\n\n"
